//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveProfiler.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EveProfiler.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/AccountBalance.xml.aspx.
        /// </summary>
        public static string Account_Balance {
            get {
                return ResourceManager.GetString("Account_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /account/AccountStatus.xml.aspx.
        /// </summary>
        public static string Account_Status {
            get {
                return ResourceManager.GetString("Account_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://image.eveonline.com/Alliance/.
        /// </summary>
        public static string Alliance_Logo {
            get {
                return ResourceManager.GetString("Alliance_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /account/APIKeyInfo.xml.aspx.
        /// </summary>
        public static string API_Key_Info {
            get {
                return ResourceManager.GetString("API_Key_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.eveonline.com.
        /// </summary>
        public static string Api_Uri {
            get {
                return ResourceManager.GetString("Api_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/AssetList.xml.aspx.
        /// </summary>
        public static string Asset_List {
            get {
                return ResourceManager.GetString("Asset_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/CalendarEventAttendees.xml.aspx.
        /// </summary>
        public static string Cal_Event_Attendees {
            get {
                return ResourceManager.GetString("Cal_Event_Attendees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://image.eveonline.com/Character/.
        /// </summary>
        public static string Character_Portrait {
            get {
                return ResourceManager.GetString("Character_Portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/CharacterSheet.xml.aspx.
        /// </summary>
        public static string Character_Sheet {
            get {
                return ResourceManager.GetString("Character_Sheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/ContactList.xml.aspx.
        /// </summary>
        public static string Contact_List {
            get {
                return ResourceManager.GetString("Contact_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/ContactNotifications.xml.aspx.
        /// </summary>
        public static string Contact_Notif {
            get {
                return ResourceManager.GetString("Contact_Notif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/Contracts.xml.aspx.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/ContractBids.xml.aspx.
        /// </summary>
        public static string Contract_Bids {
            get {
                return ResourceManager.GetString("Contract_Bids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/ContractItems.xml.aspx.
        /// </summary>
        public static string Contract_Items {
            get {
                return ResourceManager.GetString("Contract_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://image.eveonline.com/Corporation/.
        /// </summary>
        public static string Corp_Logo {
            get {
                return ResourceManager.GetString("Corp_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/FacWarStats.xml.aspx.
        /// </summary>
        public static string Factional_Warfare_Stats {
            get {
                return ResourceManager.GetString("Factional_Warfare_Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/IndustryJobs.xml.aspx.
        /// </summary>
        public static string Industry_Jobs {
            get {
                return ResourceManager.GetString("Industry_Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/Killlog.xml.aspx.
        /// </summary>
        public static string Kill_Mails {
            get {
                return ResourceManager.GetString("Kill_Mails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /account/Characters.xml.aspx.
        /// </summary>
        public static string List_Characters {
            get {
                return ResourceManager.GetString("List_Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/Locations.xml.aspx.
        /// </summary>
        public static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/MailBodies.xml.aspx.
        /// </summary>
        public static string Mail_Bodies {
            get {
                return ResourceManager.GetString("Mail_Bodies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/MailMessages.xml.aspx.
        /// </summary>
        public static string Mail_Mess_Headers {
            get {
                return ResourceManager.GetString("Mail_Mess_Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/MailingLists.xml.aspx.
        /// </summary>
        public static string Mailing_Lists {
            get {
                return ResourceManager.GetString("Mailing_Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/MarketOrders.xml.aspx.
        /// </summary>
        public static string Market_Orders {
            get {
                return ResourceManager.GetString("Market_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/Medals.xml.aspx.
        /// </summary>
        public static string Medals {
            get {
                return ResourceManager.GetString("Medals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/NotificationTexts.xml.aspx.
        /// </summary>
        public static string Notification_Text {
            get {
                return ResourceManager.GetString("Notification_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/Notifications.xml.aspx.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/Standings.xml.aspx.
        /// </summary>
        public static string NPC_Standings {
            get {
                return ResourceManager.GetString("NPC_Standings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/Research.xml.aspx.
        /// </summary>
        public static string Research {
            get {
                return ResourceManager.GetString("Research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/SkillInTraining.xml.aspx.
        /// </summary>
        public static string Skill_in_Training {
            get {
                return ResourceManager.GetString("Skill_in_Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/SkillQueue.xml.aspx.
        /// </summary>
        public static string Skill_Queue {
            get {
                return ResourceManager.GetString("Skill_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/UpcomingCalendarEvents.xml.aspx.
        /// </summary>
        public static string Upcoming_Cal_Events {
            get {
                return ResourceManager.GetString("Upcoming_Cal_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/WalletJournal.xml.aspx.
        /// </summary>
        public static string Wallet_Journal {
            get {
                return ResourceManager.GetString("Wallet_Journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /char/WalletTransactions.xml.aspx.
        /// </summary>
        public static string Wallet_Transactions {
            get {
                return ResourceManager.GetString("Wallet_Transactions", resourceCulture);
            }
        }
    }
}
